camera: hik

# odom2camera:
#   xyz: "\"0.10 0.0  0.05\""
#   rpy: "\"0.0  0.0  3.14159265\""
gimbal_odom2camera:
  xyz: "\"0.083  0.00  0.1\""
  rpy: "\"0.0  0.0  0.0\""

detector_log_level: DEBUG
tracker_log_level: INFO
# tracker_log_level: DEBUG
serial_log_level: DEBUG
